# Generated by Django 4.2.5 on 2023-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='adopt/images/cats/default.jpg', upload_to='adopt/images/cats'),
        ),
    ]
