# Generated by Django 4.2.5 on 2023-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
