# Generated by Django 4.2.5 on 2023-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
